/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fvh.reto3.view;

import java.util.ArrayList;

import com.fvh.reto3.controller.enums.Dealer;
import com.fvh.reto3.controller.classes.Product;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author fercho
 */
public class JFrameMain extends javax.swing.JFrame {
    
    ArrayList<Product> products;
    static int idProduct;
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        
        this.products = new ArrayList<Product>();
        idProduct = 1;
        jLblID.setText(idProduct + "");
        
        this.setLocationRelativeTo(null); // Centrar el JFrame
        jPnlCompany.setVisible(false);
        // Ajustar Imágenes a Buttons
        // ================================
        this.setImageButton(jBtnAdd, "src/main/java/com/fvh/reto3/view/images/plus.png");
        this.setImageButton(jBtnDel, "src/main/java/com/fvh/reto3/view/images/x-button.png");
        this.setImageButton(jBtnEdit, "src/main/java/com/fvh/reto3/view/images/pencil.png");
        this.setImageButton(jBtnClear, "src/main/java/com/fvh/reto3/view/images/cleaning.png");
        // ================================
    }
    
    // Método para ajustar la imagen al Button
    private void setImageButton(JButton jButton, String path){
        ImageIcon image = new ImageIcon(path);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(jButton.getWidth(), jButton.getHeight(), Image.SCALE_DEFAULT));
        jButton.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jLblID = new javax.swing.JLabel();
        jBtnAdd = new javax.swing.JButton();
        jBtnEdit = new javax.swing.JButton();
        jBtnDel = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProducts = new javax.swing.JList<>();
        jCmbDistributor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPnlPerson = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtName5 = new javax.swing.JTextField();
        jTxtName6 = new javax.swing.JTextField();
        jTxtName7 = new javax.swing.JTextField();
        jTxtName8 = new javax.swing.JTextField();
        jTxtName9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtName2 = new javax.swing.JTextField();
        jTxtName3 = new javax.swing.JTextField();
        jTxtName4 = new javax.swing.JTextField();
        jCmbType = new javax.swing.JComboBox<>();
        jPnlCompany = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtName10 = new javax.swing.JTextField();
        jTxtName11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel1.setText("#");

        jLabel2.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel3.setText("Distribuidor");

        jTxtName.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jLblID.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLblID.setText("-");

        jBtnAdd.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAdd.setBorder(null);
        jBtnAdd.setBorderPainted(false);
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnEdit.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEdit.setBorder(null);
        jBtnEdit.setBorderPainted(false);
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });

        jBtnDel.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDel.setBorder(null);
        jBtnDel.setBorderPainted(false);
        jBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelActionPerformed(evt);
            }
        });

        jBtnClear.setBackground(new java.awt.Color(255, 255, 255));
        jBtnClear.setBorder(null);
        jBtnClear.setBorderPainted(false);
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jListProducts.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jListProducts.setForeground(new java.awt.Color(0, 102, 102));
        jListProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListProducts);

        jCmbDistributor.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jCmbDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbDistributorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel4.setText("Lista de Productos");

        jLabel5.setText("____________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jCmbDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLblID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane1.addTab("Productos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel6.setText("Teléfono");

        jLabel7.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel7.setText("ID");

        jLabel8.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel8.setText("Dirección");

        jLabel9.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel9.setText("Persona");

        jLabel10.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel10.setText("Email");

        jPnlPerson.setBackground(new java.awt.Color(255, 255, 255));
        jPnlPerson.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel13.setText("Documento");
        jPnlPerson.add(jLabel13);
        jLabel13.setBounds(0, 10, 160, 30);

        jLabel14.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel14.setText("Primer Apellido");
        jPnlPerson.add(jLabel14);
        jLabel14.setBounds(0, 100, 210, 30);

        jLabel15.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel15.setText("Primer Nombre");
        jPnlPerson.add(jLabel15);
        jLabel15.setBounds(0, 40, 170, 30);

        jLabel17.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel17.setText("Segundo Nombre");
        jPnlPerson.add(jLabel17);
        jLabel17.setBounds(0, 70, 160, 30);

        jTxtName5.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName5ActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtName5);
        jTxtName5.setBounds(140, 10, 270, 25);

        jTxtName6.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName6ActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtName6);
        jTxtName6.setBounds(140, 40, 270, 25);

        jTxtName7.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName7ActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtName7);
        jTxtName7.setBounds(150, 70, 260, 25);

        jTxtName8.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName8ActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtName8);
        jTxtName8.setBounds(140, 100, 270, 25);

        jTxtName9.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName9ActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtName9);
        jTxtName9.setBounds(150, 130, 260, 25);

        jLabel16.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel16.setText("Segundo Apellido");
        jPnlPerson.add(jLabel16);
        jLabel16.setBounds(0, 130, 143, 30);

        jTxtName2.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName2ActionPerformed(evt);
            }
        });

        jTxtName3.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName3ActionPerformed(evt);
            }
        });

        jTxtName4.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName4ActionPerformed(evt);
            }
        });

        jCmbType.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jCmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Jurídica" }));
        jCmbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbTypeItemStateChanged(evt);
            }
        });
        jCmbType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCmbTypeMouseReleased(evt);
            }
        });
        jCmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTypeActionPerformed(evt);
            }
        });

        jPnlCompany.setBackground(new java.awt.Color(255, 255, 255));
        jPnlCompany.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel12.setText("Razón Social");
        jPnlCompany.add(jLabel12);
        jLabel12.setBounds(10, 10, 120, 30);

        jLabel11.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel11.setText("NIT");
        jPnlCompany.add(jLabel11);
        jLabel11.setBounds(10, 40, 70, 30);

        jTxtName10.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName10ActionPerformed(evt);
            }
        });
        jPnlCompany.add(jTxtName10);
        jTxtName10.setBounds(120, 10, 280, 25);

        jTxtName11.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName11ActionPerformed(evt);
            }
        });
        jPnlCompany.add(jTxtName11);
        jTxtName11.setBounds(120, 40, 280, 25);

        jLabel18.setText("____________________________________________________________________");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPnlPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jPnlCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtName4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTxtName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnlCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNameActionPerformed

    // Mëtodo para agregar un Producto
    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        String name = jTxtName.getText();
        String dealer = jCmbDistributor.getSelectedItem().toString();
        
        if(jTxtName.getText().trim().length() != 0){
            // Creación del producto
            Product product = new Product(idProduct, name, this.toDealer(dealer));
            // Agregar el producto a la ArrayList
            this.products.add(product);

            // Incremento del idProduct 
            idProduct++;

            // Actualizar el listado de Productos
            this.updateProductList();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre para el producto...");
        }
    }//GEN-LAST:event_jBtnAddActionPerformed
    
    // Método para actualizar el listado de Productos
    private void updateProductList(){
        // Creación de DefaultListModel, necesario para agregar al comboBox
        DefaultListModel listModel = new DefaultListModel();

        for (Product pro: this.products) {
            // Añadir cada nombre de Producto a la lista
            listModel.addElement(pro.getDescription());
        }
        jListProducts.setModel(listModel);

        // Limpieza del formulario
        this.clearForm();
    }
    
    // Método para limpiar el formulario
    private void clearForm(){
        jLblID.setText(idProduct + "");
        jTxtName.setText("");
        jCmbDistributor.setSelectedIndex(0);
        jTxtName.requestFocus();
    }
    
    // Método para convertir un String a Dealer
    private Dealer toDealer(String dealer){
        switch(dealer){
            case "HP": return Dealer.HP; 
            case "CISCO": return Dealer.CISCO; 
            case "LEXMARK": return Dealer.LEXMARK; 
            case "VMWARE": return Dealer.VMWARE; 
        }
        return Dealer.HP;
    }
    
    private void jCmbDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbDistributorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Cargar el comboBox de Dealers
        for(Dealer dealer: Dealer.values())
           this.jCmbDistributor.addItem(dealer.toString());
    }//GEN-LAST:event_formWindowOpened

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        this.clearForm();
    }//GEN-LAST:event_jBtnClearActionPerformed

    // Seleccionar un Producto
    private void jListProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProductsMouseClicked
        if(jListProducts.getSelectedIndex() > -1){
            Product product = this.products.get(jListProducts.getSelectedIndex());
            jTxtName.setText(product.getName());
            jLblID.setText(product.getId() + "");
            jCmbDistributor.setSelectedItem(product.getDealer().toString());
        }
    }//GEN-LAST:event_jListProductsMouseClicked

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
        if(jTxtName.getText().trim().length() != 0){
            for (Product prod: this.products) {
                if(prod.getId() == Long.parseLong(jLblID.getText().toString())){
                    prod.setName(jTxtName.getText());
                    prod.setDealer(this.toDealer(jCmbDistributor.getSelectedItem().toString()));
                }
            }

            // Actualizar el listado de Productos
            this.updateProductList();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre para el producto...");
        }
    }//GEN-LAST:event_jBtnEditActionPerformed

    // Mëtodo para eliminar un Producto
    private void jBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelActionPerformed
        Product prodSelected = null;
        for (Product prod: this.products) {
            if(prod.getId() == Long.parseLong(jLblID.getText().toString())){
                prodSelected = prod;
            }
        }
        if(prodSelected != null)
            this.products.remove(prodSelected);

        // Actualizar el listado de Productos
        this.updateProductList();
    }//GEN-LAST:event_jBtnDelActionPerformed

    private void jTxtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName2ActionPerformed

    private void jTxtName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName3ActionPerformed

    private void jTxtName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName4ActionPerformed

    private void jCmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTypeActionPerformed
        if(jCmbType.getSelectedItem().toString() == "Jurídica"){
            jPnlCompany.setVisible(true);
            jPnlPerson.setVisible(false);
        }
        else{
            jPnlCompany.setVisible(false);
            jPnlPerson.setVisible(true);
        }
    }//GEN-LAST:event_jCmbTypeActionPerformed

    private void jTxtName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName5ActionPerformed

    private void jTxtName6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName6ActionPerformed

    private void jTxtName7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName7ActionPerformed

    private void jTxtName8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName8ActionPerformed

    private void jTxtName9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName9ActionPerformed

    private void jTxtName10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName10ActionPerformed

    private void jTxtName11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName11ActionPerformed

    private void jCmbTypeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbTypeMouseReleased
        
    }//GEN-LAST:event_jCmbTypeMouseReleased

    private void jCmbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbTypeItemStateChanged
     
    }//GEN-LAST:event_jCmbTypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDel;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JComboBox<String> jCmbDistributor;
    private javax.swing.JComboBox<String> jCmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblID;
    private javax.swing.JList<String> jListProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlCompany;
    private javax.swing.JPanel jPnlPerson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtName10;
    private javax.swing.JTextField jTxtName11;
    private javax.swing.JTextField jTxtName2;
    private javax.swing.JTextField jTxtName3;
    private javax.swing.JTextField jTxtName4;
    private javax.swing.JTextField jTxtName5;
    private javax.swing.JTextField jTxtName6;
    private javax.swing.JTextField jTxtName7;
    private javax.swing.JTextField jTxtName8;
    private javax.swing.JTextField jTxtName9;
    // End of variables declaration//GEN-END:variables
}
