/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fvh.reto3.view;

import java.util.ArrayList;

import com.fvh.reto3.controller.enums.Dealer;
import com.fvh.reto3.controller.classes.Product;
import com.fvh.reto3.controller.classes.abst.Customer;
import com.fvh.reto3.controller.classes.Person;
import com.fvh.reto3.controller.classes.Company;

import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author fercho
 */
public class JFrameMain extends javax.swing.JFrame {
    
    boolean customerType; // false: Person | true: Company
    
    ArrayList<Product> products;
    ArrayList<Customer> customers;
    
    // Variables statics cuyo fin es mantener un consecutivo en productos y clientes
    static int idProduct;
    static int idCustomer;
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        
        this.products = new ArrayList<Product>();
        this.customers = new ArrayList<Customer>();
        
        idProduct = 1;
        idCustomer = 1;
        this.customerType = false;
        
        jLblID.setText(idProduct + "");
        jLblIDCus.setText(idCustomer + "");
        
        this.setLocationRelativeTo(null); // Centrar el JFrame
        jPnlCompany.setVisible(false);
        // Ajustar Imágenes a Buttons
        // ================================
        this.setImageButton(jBtnAdd, "src/main/java/com/fvh/reto3/view/images/plus.png");
        this.setImageButton(jBtnDel, "src/main/java/com/fvh/reto3/view/images/x-button.png");
        this.setImageButton(jBtnEdit, "src/main/java/com/fvh/reto3/view/images/pencil.png");
        this.setImageButton(jBtnClear, "src/main/java/com/fvh/reto3/view/images/cleaning.png");
        this.setImageButton(jBtnAddCus, "src/main/java/com/fvh/reto3/view/images/plus.png");
        this.setImageButton(jBtnDelCus, "src/main/java/com/fvh/reto3/view/images/x-button.png");
        this.setImageButton(jBtnEditCus, "src/main/java/com/fvh/reto3/view/images/pencil.png");
        this.setImageButton(jBtnClearCus, "src/main/java/com/fvh/reto3/view/images/cleaning.png");
        // ================================
    }
    
    // Método para ajustar la imagen al Button
    private void setImageButton(JButton jButton, String path){
        ImageIcon image = new ImageIcon(path);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(jButton.getWidth(), jButton.getHeight(), Image.SCALE_DEFAULT));
        jButton.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jLblID = new javax.swing.JLabel();
        jBtnAdd = new javax.swing.JButton();
        jBtnEdit = new javax.swing.JButton();
        jBtnDel = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProducts = new javax.swing.JList<>();
        jCmbDistributor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLblIDCus = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jTxtPhone = new javax.swing.JTextField();
        jCmbType = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jBtnAddCus = new javax.swing.JButton();
        jBtnEditCus = new javax.swing.JButton();
        jBtnDelCus = new javax.swing.JButton();
        jBtnClearCus = new javax.swing.JButton();
        jPnlPerson = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtDocument = new javax.swing.JTextField();
        jTxtFName = new javax.swing.JTextField();
        jTxtSName = new javax.swing.JTextField();
        jTxtFSurname = new javax.swing.JTextField();
        jTxtSSurname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPnlCompany = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtRegName = new javax.swing.JTextField();
        jTxtNit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCustomers = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel1.setText("#");

        jLabel2.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel3.setText("Distribuidor");

        jTxtName.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jLblID.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLblID.setText("-");

        jBtnAdd.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAdd.setBorder(null);
        jBtnAdd.setBorderPainted(false);
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnEdit.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEdit.setBorder(null);
        jBtnEdit.setBorderPainted(false);
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });

        jBtnDel.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDel.setBorder(null);
        jBtnDel.setBorderPainted(false);
        jBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelActionPerformed(evt);
            }
        });

        jBtnClear.setBackground(new java.awt.Color(255, 255, 255));
        jBtnClear.setBorder(null);
        jBtnClear.setBorderPainted(false);
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jListProducts.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jListProducts.setForeground(new java.awt.Color(0, 102, 102));
        jListProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListProducts);

        jCmbDistributor.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jCmbDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbDistributorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel4.setText("Lista de Productos");

        jLabel5.setText("____________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jCmbDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLblID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel6.setText("Teléfono");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 110, 30);

        jLblIDCus.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLblIDCus.setText("ID");
        jPanel2.add(jLblIDCus);
        jLblIDCus.setBounds(120, 10, 70, 30);

        jLabel8.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel8.setText("Dirección");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 40, 100, 30);

        jLabel9.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel9.setText("Persona");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 130, 70, 30);

        jLabel10.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel10.setText("Email");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 100, 80, 30);

        jTxtEmail.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtEmail);
        jTxtEmail.setBounds(120, 100, 270, 25);

        jTxtAddress.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAddressActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtAddress);
        jTxtAddress.setBounds(120, 40, 270, 25);

        jTxtPhone.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtPhone);
        jTxtPhone.setBounds(120, 70, 270, 25);

        jCmbType.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jCmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Jurídica" }));
        jCmbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbTypeItemStateChanged(evt);
            }
        });
        jCmbType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCmbTypeMouseReleased(evt);
            }
        });
        jCmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTypeActionPerformed(evt);
            }
        });
        jPanel2.add(jCmbType);
        jCmbType.setBounds(120, 130, 270, 27);

        jLabel18.setText("________________________________________________________________");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 145, 410, 20);

        jBtnAddCus.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAddCus.setBorder(null);
        jBtnAddCus.setBorderPainted(false);
        jBtnAddCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddCusActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAddCus);
        jBtnAddCus.setBounds(430, 40, 30, 30);

        jBtnEditCus.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEditCus.setBorder(null);
        jBtnEditCus.setBorderPainted(false);
        jBtnEditCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditCusActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnEditCus);
        jBtnEditCus.setBounds(430, 90, 30, 30);

        jBtnDelCus.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDelCus.setBorder(null);
        jBtnDelCus.setBorderPainted(false);
        jBtnDelCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelCusActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnDelCus);
        jBtnDelCus.setBounds(430, 150, 30, 30);

        jBtnClearCus.setBackground(new java.awt.Color(255, 255, 255));
        jBtnClearCus.setBorder(null);
        jBtnClearCus.setBorderPainted(false);
        jBtnClearCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearCusActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnClearCus);
        jBtnClearCus.setBounds(440, 210, 30, 30);

        jPnlPerson.setBackground(new java.awt.Color(255, 255, 255));
        jPnlPerson.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel13.setText("Documento");
        jPnlPerson.add(jLabel13);
        jLabel13.setBounds(0, 10, 160, 30);

        jLabel14.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel14.setText("Primer Apellido");
        jPnlPerson.add(jLabel14);
        jLabel14.setBounds(0, 100, 210, 30);

        jLabel15.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel15.setText("Primer Nombre");
        jPnlPerson.add(jLabel15);
        jLabel15.setBounds(0, 40, 170, 30);

        jLabel17.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel17.setText("Segundo Nombre");
        jPnlPerson.add(jLabel17);
        jLabel17.setBounds(0, 70, 160, 30);

        jTxtDocument.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDocumentActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtDocument);
        jTxtDocument.setBounds(150, 10, 240, 25);

        jTxtFName.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFNameActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtFName);
        jTxtFName.setBounds(150, 40, 240, 25);

        jTxtSName.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSNameActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtSName);
        jTxtSName.setBounds(150, 70, 240, 25);

        jTxtFSurname.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtFSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFSurnameActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtFSurname);
        jTxtFSurname.setBounds(150, 100, 240, 25);

        jTxtSSurname.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtSSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSSurnameActionPerformed(evt);
            }
        });
        jPnlPerson.add(jTxtSSurname);
        jTxtSSurname.setBounds(150, 130, 240, 25);

        jLabel16.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel16.setText("Segundo Apellido");
        jPnlPerson.add(jLabel16);
        jLabel16.setBounds(0, 130, 143, 30);

        jPanel2.add(jPnlPerson);
        jPnlPerson.setBounds(6, 156, 400, 160);

        jPnlCompany.setBackground(new java.awt.Color(255, 255, 255));
        jPnlCompany.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel12.setText("Razón Social");
        jPnlCompany.add(jLabel12);
        jLabel12.setBounds(0, 0, 120, 30);

        jLabel11.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel11.setText("NIT");
        jPnlCompany.add(jLabel11);
        jLabel11.setBounds(0, 30, 70, 30);

        jTxtRegName.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtRegName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRegNameActionPerformed(evt);
            }
        });
        jPnlCompany.add(jTxtRegName);
        jTxtRegName.setBounds(130, 0, 250, 25);

        jTxtNit.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTxtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNitActionPerformed(evt);
            }
        });
        jPnlCompany.add(jTxtNit);
        jTxtNit.setBounds(130, 30, 250, 25);

        jPanel2.add(jPnlCompany);
        jPnlCompany.setBounds(10, 170, 420, 76);

        jLabel19.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel19.setText("ID");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 10, 70, 30);

        jListCustomers.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(jListCustomers);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(510, 40, 320, 270);

        jTabbedPane1.addTab("Clientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNameActionPerformed

    // Mëtodo para agregar un Producto
    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        String name = jTxtName.getText();
        String dealer = jCmbDistributor.getSelectedItem().toString();
        
        if(jTxtName.getText().trim().length() != 0){
            // Creación del producto
            Product product = new Product(idProduct, name, this.toDealer(dealer));
            // Agregar el producto a la ArrayList
            this.products.add(product);

            // Incremento del idProduct 
            idProduct++;

            // Actualizar el listado de Productos
            this.updateProductList();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre para el producto...");
        }
    }//GEN-LAST:event_jBtnAddActionPerformed
    
    // Método para actualizar el listado de Productos
    private void updateProductList(){
        // Creación de DefaultListModel, necesario para agregar al comboBox
        DefaultListModel listModel = new DefaultListModel();

        for (Product pro: this.products) {
            // Añadir cada nombre de Producto a la lista
            listModel.addElement(pro.getDescription());
        }
        jListProducts.setModel(listModel);

        // Limpieza del formulario
        this.clearForm();
    }
    
    // Método para limpiar el formulario de Producto
    private void clearForm(){
        jLblID.setText(idProduct + "");
        jTxtName.setText("");
        jCmbDistributor.setSelectedIndex(0);
        jTxtName.requestFocus();
    }
    
    // Método para limpiar el formulario de Cliente
    private void clearCustomerForm(){
        jTxtDocument.setText("");
        jTxtFName.setText("");
        jTxtSName.setText("");
        jTxtFSurname.setText("");
        jTxtSSurname.setText("");
        jTxtAddress.setText("");
        jTxtPhone.setText("");
        jTxtEmail.setText("");
        jTxtRegName.setText("");
        jTxtNit.setText("");
        jLblIDCus.setText(idCustomer + "");
        jCmbType.setSelectedIndex(0);
        this.customerType = false;
    }
    
    // Método para convertir un String a Dealer
    private Dealer toDealer(String dealer){
        switch(dealer){
            case "HP": return Dealer.HP; 
            case "CISCO": return Dealer.CISCO; 
            case "LEXMARK": return Dealer.LEXMARK; 
            case "VMWARE": return Dealer.VMWARE; 
        }
        return Dealer.HP;
    }
    
    private void jCmbDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbDistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbDistributorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Cargar el comboBox de Dealers
        for(Dealer dealer: Dealer.values())
           this.jCmbDistributor.addItem(dealer.toString());
    }//GEN-LAST:event_formWindowOpened

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        this.clearForm();
    }//GEN-LAST:event_jBtnClearActionPerformed

    // Seleccionar un Producto
    private void jListProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProductsMouseClicked
        if(jListProducts.getSelectedIndex() > -1){
            Product product = this.products.get(jListProducts.getSelectedIndex());
            jTxtName.setText(product.getName());
            jLblID.setText(product.getId() + "");
            jCmbDistributor.setSelectedItem(product.getDealer().toString());
        }
    }//GEN-LAST:event_jListProductsMouseClicked

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
        if(jTxtName.getText().trim().length() != 0){
            for (Product prod: this.products) {
                if(prod.getId() == Long.parseLong(jLblID.getText().toString())){
                    prod.setName(jTxtName.getText());
                    prod.setDealer(this.toDealer(jCmbDistributor.getSelectedItem().toString()));
                }
            }

            // Actualizar el listado de Productos
            this.updateProductList();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre para el producto...");
        }
    }//GEN-LAST:event_jBtnEditActionPerformed

    // Mëtodo para eliminar un Producto
    private void jBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelActionPerformed
        Product prodSelected = null;
        for (Product prod: this.products) {
            if(prod.getId() == Long.parseLong(jLblID.getText().toString())){
                prodSelected = prod;
            }
        }
        if(prodSelected != null)
            this.products.remove(prodSelected);

        // Actualizar el listado de Productos
        this.updateProductList();
    }//GEN-LAST:event_jBtnDelActionPerformed

    // Método para verficar si un formulario de creacion de cliente está correctamente diligenciado ó no
    private boolean isCorrectCustomerForm(){
        boolean check = false;
        if(
              jTxtAddress.getText().trim().length() > 0 &&
              jTxtPhone.getText().trim().length() > 0 &&
              jTxtEmail.getText().trim().length() > 0 
          ){
            if(this.customerType){ // Company
                if(jTxtRegName.getText().trim().length() > 0 && jTxtNit.getText().trim().length() > 0){
                    check = true;
                }
            }
            else{ // Person
                if(
                        jTxtDocument.getText().trim().length() > 0 &&
                        jTxtFName.getText().trim().length() > 0 &&
                        jTxtSName.getText().trim().length() > 0 &&
                        jTxtFSurname.getText().trim().length()> 0 &&
                        jTxtSSurname.getText().trim().length()> 0 
                  ){
                   check = true; 
                }
            }
            
        }
        
        return check;
    }
    
    private void jTxtSSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSSurnameActionPerformed

    private void jTxtFSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFSurnameActionPerformed

    private void jTxtSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSNameActionPerformed

    private void jTxtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFNameActionPerformed

    private void jTxtDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDocumentActionPerformed

    private void jBtnClearCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnClearCusActionPerformed

    private void jBtnDelCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDelCusActionPerformed

    private void jBtnEditCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEditCusActionPerformed

    // Método para agregar Clientes
    private void jBtnAddCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddCusActionPerformed
        if(this.isCorrectCustomerForm()){
            Customer customer;
            if(this.customerType){ // Company
                customer = new Company(
                                        jTxtRegName.getText(),
                                        jTxtNit.getText(),
                                        idCustomer,
                                        jTxtAddress.getText(),
                                        jTxtPhone.getText(),
                                        jTxtEmail.getText()
                                       );
            }
            else{ // Person
                customer = new Person(
                                        jTxtDocument.getText(),
                                        jTxtFName.getText(),
                                        jTxtSName.getText(),
                                        jTxtFSurname.getText(),
                                        jTxtSSurname.getText(),
                                        idCustomer,
                                        jTxtAddress.getText(),
                                        jTxtPhone.getText(),
                                        jTxtEmail.getText()
                                      );
            }
            this.customers.add(customer);
            idCustomer++;
            this.updateCustomerList();
        }
        else{
            JOptionPane.showMessageDialog(null, "No haz diligenciado el formulario completo para crear un Cliente");
        }
    }//GEN-LAST:event_jBtnAddCusActionPerformed
    
    // Método para actualizar el listado de Clientes
    private void updateCustomerList(){
        // Creación de DefaultListModel, necesario para agregar al comboBox
        DefaultListModel listModel = new DefaultListModel();

        for (Customer cli: this.customers) {
            // Añadir cada nombre de Producto a la lista
            listModel.addElement(cli.getDescription());
        }
        jListCustomers.setModel(listModel);

        // Limpieza del formulario
        this.clearCustomerForm();
    }
    
    private void jTxtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNitActionPerformed

    private void jTxtRegNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRegNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRegNameActionPerformed

    private void jCmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTypeActionPerformed
        if(jCmbType.getSelectedItem().toString() == "Jurídica"){
            jPnlCompany.setVisible(true);
            jPnlPerson.setVisible(false);
            this.customerType = true;
        }
        else{
            jPnlCompany.setVisible(false);
            jPnlPerson.setVisible(true);
            this.customerType = false;
        }
    }//GEN-LAST:event_jCmbTypeActionPerformed

    private void jCmbTypeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbTypeMouseReleased

    }//GEN-LAST:event_jCmbTypeMouseReleased

    private void jCmbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbTypeItemStateChanged

    }//GEN-LAST:event_jCmbTypeItemStateChanged

    private void jTxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPhoneActionPerformed

    private void jTxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAddressActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnAddCus;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnClearCus;
    private javax.swing.JButton jBtnDel;
    private javax.swing.JButton jBtnDelCus;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JButton jBtnEditCus;
    private javax.swing.JComboBox<String> jCmbDistributor;
    private javax.swing.JComboBox<String> jCmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblID;
    private javax.swing.JLabel jLblIDCus;
    private javax.swing.JList<String> jListCustomers;
    private javax.swing.JList<String> jListProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlCompany;
    private javax.swing.JPanel jPnlPerson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtDocument;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtFName;
    private javax.swing.JTextField jTxtFSurname;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtNit;
    private javax.swing.JTextField jTxtPhone;
    private javax.swing.JTextField jTxtRegName;
    private javax.swing.JTextField jTxtSName;
    private javax.swing.JTextField jTxtSSurname;
    // End of variables declaration//GEN-END:variables
}
